<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="WebDriver" duration-ms="16273" started-at="2019-03-09T09:40:11Z" finished-at="2019-03-09T09:40:27Z">
    <groups>
    </groups>
    <test name="test" duration-ms="16273" started-at="2019-03-09T09:40:11Z" finished-at="2019-03-09T09:40:27Z">
      <class name="TestPkg.test1">
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:TestPkg.test1@23ceabc1]" name="beforeMethod" is-config="true" duration-ms="3752" started-at="2019-03-09T12:40:11Z" finished-at="2019-03-09T12:40:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="checkgoogleURL()[pri:0, instance:TestPkg.test1@23ceabc1]" name="checkgoogleURL" duration-ms="2523" started-at="2019-03-09T12:40:15Z" finished-at="2019-03-09T12:40:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkgoogleURL -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:TestPkg.test1@23ceabc1]" name="afterMethod" is-config="true" duration-ms="1029" started-at="2019-03-09T12:40:17Z" finished-at="2019-03-09T12:40:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:TestPkg.test1@23ceabc1]" name="beforeMethod" is-config="true" duration-ms="3307" started-at="2019-03-09T12:40:18Z" finished-at="2019-03-09T12:40:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="loginEmail()[pri:0, instance:TestPkg.test1@23ceabc1]" name="loginEmail" duration-ms="4616" started-at="2019-03-09T12:40:22Z" finished-at="2019-03-09T12:40:26Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [https://www.google.com/?gws_rd=sslfailed] but found [http://www.google.com]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [https://www.google.com/?gws_rd=sslfailed] but found [http://www.google.com]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at TestPkg.test1.loginEmail(test1.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginEmail -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:TestPkg.test1@23ceabc1]" name="afterMethod" is-config="true" duration-ms="1025" started-at="2019-03-09T12:40:26Z" finished-at="2019-03-09T12:40:27Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- TestPkg.test1 -->
    </test> <!-- test -->
  </suite> <!-- WebDriver -->
</testng-results>
